//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TextualProcessor.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TextualProcessor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a hacer el oso|_hacer_el_oso
        ///Hacer el oso|_hacer_el_oso
        ///hizo el oso|_hacer_el_oso
        ///Ángela Maria Robledo|angela
        ///Gustavo Petro|_gustavo_petro
        ///Ángela María Robledo|angela
        ///Ángela Robledo|angela
        ///María José Pizarro|maria_jose
        ///Pepe Mujica|_pepe_mujica
        ///Angela María Robledo|angela
        ///mano peluda|_mano_peluda
        ///enfoque constructivo|_enfoque_constructivo
        ///Osama Bin Laden|_Osama_Bin_Laden
        ///ruta sol|_ruta_sol
        ///Coalición Colombia|_Coalicion_Colombia
        ///¡Qué peligro!|_¡Qué_peligro!
        ///fraude electoral|_fraude_electoral
        ///Iv [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string compoundWords {
            get {
                return ResourceManager.GetString("compoundWords", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Definitivamente en la pol?tica la lealtad es dif?cil de conseguir, la se?ora Robledo se supone es del partido verde, que a su vez apoyo a Fajardo y que hoy crece en el senado gracias a Mokus.|definitiv lealt  robled supone part verde  apoy fajard crece sen graci mokus    |3/16/2018|Fajardo|Facebook
        ///UN MATEM?TICO NUESTRO  PRESIDENTE...DEL CARAJO !!!...ADELANTE PROFE Sergio Fajardo Presidente 2018-2022.|matem tic nuestr  presidente   del caraj       adel profe sergi _fajardo_presidente 2018-2022    |3/27/201 [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string lemmatizedPublications {
            get {
                return ResourceManager.GetString("lemmatizedPublications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a a
        ///acá
        ///ahí
        ///ajena
        ///ajenas
        ///ajeno
        ///ajenos
        ///al
        ///algo
        ///algún
        ///alguna
        ///algunas
        ///alguno
        ///algunos
        ///allá
        ///alli
        ///allí
        ///ambos
        ///ampleamos
        ///ante
        ///antes
        ///aquel
        ///aquella
        ///aquellas
        ///aquello
        ///aquellos
        ///aqui
        ///aquí
        ///arriba
        ///asi
        ///atras
        ///aun
        ///aunque
        ///bajo
        ///bastante
        ///cabe
        ///cada
        ///casi
        ///cierta
        ///ciertas
        ///cierto
        ///ciertos
        ///como
        ///cómo
        ///con
        ///conmigo
        ///conseguimos
        ///conseguir
        ///consigo
        ///consigue
        ///consiguen
        ///consigues
        ///contigo
        ///contra
        ///cual
        ///cuales
        ///cualquier
        ///cualquiera
        ///cualquieras
        ///cuan
        ///cuán
        ///cuando
        ///cuanta
        ///cuánta
        ///cuantas
        ///cuántas        /// [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string stopWords {
            get {
                return ResourceManager.GetString("stopWords", resourceCulture);
            }
        }
    }
}
