//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Qualification.Properties {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Qualification.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sergio|0
        ///Fajardo|0
        ///hacer_el_oso|-2
        ///Bogota|0
        ///Petro|0
        ///populista|-4
        ///convertira|-2
        ///Colombia|0
        ///Venezuela|-3
        ///perdiendo|-2
        ///gran|2
        ///cantidad|0
        ///votantes|0
        ///falta|-3
        ///decision|0
        ///Claudia|0
        ///complementa|2
        ///mejor|2
        ///manera|0
        ///campaÃ±a|0
        ///de|0
        ///|0
        ///invit|0
        ///leer|0
        ///program|0
        ///gobiern|0
        ///@petrogustav|0
        ///Si|0
        ///encuentr|0
        ///propuest|0
        ///cuent|0
        ///ide|1
        ///cambi|4
        ///histori|0
        ///empez|0
        ///pon|0
        ///trabas|-1
        ///alcaldi|0
        ///imped|-2
        ///present|0
        ///_gustavo_petro|0
        ///parque|1
        ///exij|-1
        ///alcalde|0
        ///@eleazargoncas|0
        ///funcionari|0
        ///cumpl [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string Diccionario {
            get {
                return ResourceManager.GetString("Diccionario", resourceCulture);
            }
        }
    }
}
